# Site settings
title: Huang-Libo's Blog
header-img: img/post-bg-04.jpg
email: LiboHwang+IM@gmail.com
copyright_name: Huang-Libo
description: "黄立波，iOS开发者"
baseurl: ""
url: "http://huanglibo.com"
twitter_username: huanglb
github_username: Huang-Libo 
facebook_username: 100007182639985 
email_username:  LiboHwang+IM@gmail.com

# Google Analytics
# To enable google analytics, uncomment below line with a valid Google Tracking ID
# google_tracking_id:

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 20
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
